# Generated by Django 3.1.3 on 2020-11-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', height_field='120', upload_to='', width_field='150'),
        ),
        migrations.AlterField(
            model_name='article',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.magasin'),
        ),
    ]
